apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "myapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "myapp.name" . }}
    spec:
      containers:
        - name: myapp-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
